// <auto-generated />
using System;
using CashTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashTrack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.BankApp", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasAlternateKey("PackageName")
                        .HasName("AK_BankApps_PackageName");

                    b.HasIndex("PackageName")
                        .IsUnique()
                        .HasDatabaseName("UX_BankApps_PackageName");

                    b.ToTable("BankApps", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "VCB",
                            Color = "#006A4E",
                            Name = "Ngan hang TMCP Ngoai Thuong Viet Nam",
                            PackageName = "com.VCB",
                            ShortName = "Vietcombank"
                        },
                        new
                        {
                            Code = "MB",
                            Color = "#0066B3",
                            Name = "Ngan hang TMCP Quan Doi",
                            PackageName = "com.mbmobile",
                            ShortName = "MB Bank"
                        },
                        new
                        {
                            Code = "TCB",
                            Color = "#E01E3C",
                            Name = "Ngan hang TMCP Ky Thuong Viet Nam",
                            PackageName = "vn.com.techcombank.bb.app",
                            ShortName = "Techcombank"
                        },
                        new
                        {
                            Code = "ACB",
                            Color = "#004C6D",
                            Name = "Ngan hang TMCP A Chau",
                            PackageName = "mobile.acb.com.vn",
                            ShortName = "ACB"
                        },
                        new
                        {
                            Code = "VPB",
                            Color = "#00A859",
                            Name = "Ngan hang TMCP Viet Nam Thinh Vuong",
                            PackageName = "com.vnpay.vpbankonline",
                            ShortName = "VPBank"
                        },
                        new
                        {
                            Code = "BIDV",
                            Color = "#003087",
                            Name = "Ngan hang TMCP Dau Tu va Phat Trien Viet Nam",
                            PackageName = "com.vnpay.bidv",
                            ShortName = "BIDV"
                        },
                        new
                        {
                            Code = "VTB",
                            Color = "#0033A0",
                            Name = "Ngan hang TMCP Cong Thuong Viet Nam",
                            PackageName = "com.vietinbank.ipay",
                            ShortName = "Vietinbank"
                        },
                        new
                        {
                            Code = "TPB",
                            Color = "#6D28D9",
                            Name = "Ngan hang TMCP Tien Phong",
                            PackageName = "com.tpb.mb.gprsandroid",
                            ShortName = "TPBank"
                        },
                        new
                        {
                            Code = "MOMO",
                            Color = "#A50064",
                            Name = "Vi MoMo",
                            PackageName = "com.mservice.momotransfer",
                            ShortName = "MoMo"
                        },
                        new
                        {
                            Code = "VNPAY",
                            Color = "#004C6D",
                            Name = "VNPay",
                            PackageName = "vn.com.vnpay.customer",
                            ShortName = "VNPay"
                        },
                        new
                        {
                            Code = "ZALOPAY",
                            Color = "#0068FF",
                            Name = "ZaloPay",
                            PackageName = "vn.com.vng.zalopay",
                            ShortName = "ZaloPay"
                        });
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.BankNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppPackage")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdvertisement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBankingNotification")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NotificationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParsedAmountMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedMerchant")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedTransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedType")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankCode");

                    b.HasIndex("ParsedTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_BankNotifications_ParsedTransactionId");

                    b.HasIndex("UserId", "BankCode")
                        .HasDatabaseName("IX_BankNotifications_UserId_BankCode");

                    b.HasIndex("UserId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_BankNotifications_UserId_ExternalId");

                    b.HasIndex("UserId", "Processed")
                        .HasDatabaseName("IX_BankNotifications_UserId_Processed");

                    b.HasIndex("UserId", "RawTextHash")
                        .IsUnique()
                        .HasDatabaseName("UX_BankNotifications_UserId_RawTextHash");

                    b.HasIndex("UserId", "AppPackage", "NotificationTimeUtc")
                        .HasDatabaseName("IX_BankNotifications_UserId_AppPackage_NotificationTimeUtc");

                    b.ToTable("BankNotifications", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.CategoryBudget", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimitMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoryBudgets_UserId_CategoryId");

                    b.ToTable("CategoryBudgets", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ClientStorageEnvelope", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_ClientStorageEnvelopes_UpdatedAtUtc");

                    b.HasIndex("UserId", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ClientStorageEnvelopes_UserId_StorageKey");

                    b.ToTable("ClientStorageEnvelopes", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ImportBatches_Status");

                    b.HasIndex("UserId", "StartedAtUtc")
                        .HasDatabaseName("IX_ImportBatches_UserId_StartedAtUtc");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ImportRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTransactionId")
                        .HasDatabaseName("IX_ImportRows_ExternalTransactionId");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_ImportRows_TransactionId");

                    b.HasIndex("ImportBatchId", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ImportRows_ImportBatchId_RowNumber");

                    b.ToTable("ImportRows", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportBatchId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merchant")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawNotification")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawNotificationHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankCode");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DeletedAtUtc")
                        .HasDatabaseName("IX_Transactions_DeletedAtUtc");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Transactions_IsDeleted");

                    b.HasIndex("UserId", "BankCode")
                        .HasDatabaseName("IX_Transactions_UserId_BankCode");

                    b.HasIndex("UserId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Transactions_UserId_ExternalId");

                    b.HasIndex("UserId", "RawNotificationHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Transactions_UserId_RawNotificationHash");

                    b.HasIndex("UserId", "Source")
                        .HasDatabaseName("IX_Transactions_UserId_Source");

                    b.HasIndex("UserId", "TransactionDateUtc")
                        .HasDatabaseName("IX_Transactions_UserId_TransactionDateUtc");

                    b.HasIndex("UserId", "CategoryId", "TransactionDateUtc")
                        .HasDatabaseName("IX_Transactions_UserId_CategoryId_TransactionDateUtc");

                    b.HasIndex("UserId", "Type", "TransactionDateUtc")
                        .HasDatabaseName("IX_Transactions_UserId_Type_TransactionDateUtc");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradientEnd")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradientStart")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelVi")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_TransactionCategories_SortOrder");

                    b.ToTable("TransactionCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "food",
                            Color = "#f97316",
                            GradientEnd = "#ea580c",
                            GradientStart = "#fb923c",
                            Icon = "restaurant",
                            Label = "Food & Dining",
                            LabelVi = "An uong",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "shopping",
                            Color = "#ec4899",
                            GradientEnd = "#db2777",
                            GradientStart = "#f472b6",
                            Icon = "shopping-bag",
                            Label = "Shopping",
                            LabelVi = "Mua sam",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "transport",
                            Color = "#3b82f6",
                            GradientEnd = "#2563eb",
                            GradientStart = "#60a5fa",
                            Icon = "directions-car",
                            Label = "Transportation",
                            LabelVi = "Di chuyen",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "entertainment",
                            Color = "#a855f7",
                            GradientEnd = "#9333ea",
                            GradientStart = "#c084fc",
                            Icon = "movie",
                            Label = "Entertainment",
                            LabelVi = "Giai tri",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "bills",
                            Color = "#ef4444",
                            GradientEnd = "#dc2626",
                            GradientStart = "#f87171",
                            Icon = "receipt",
                            Label = "Bills & Utilities",
                            LabelVi = "Hoa don",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "health",
                            Color = "#14b8a6",
                            GradientEnd = "#0d9488",
                            GradientStart = "#2dd4bf",
                            Icon = "local-hospital",
                            Label = "Health & Medical",
                            LabelVi = "Suc khoe",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "education",
                            Color = "#6366f1",
                            GradientEnd = "#4f46e5",
                            GradientStart = "#818cf8",
                            Icon = "school",
                            Label = "Education",
                            LabelVi = "Giao duc",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "salary",
                            Color = "#22c55e",
                            GradientEnd = "#16a34a",
                            GradientStart = "#4ade80",
                            Icon = "account-balance-wallet",
                            Label = "Salary",
                            LabelVi = "Luong",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "transfer",
                            Color = "#06b6d4",
                            GradientEnd = "#0891b2",
                            GradientStart = "#22d3ee",
                            Icon = "swap-horiz",
                            Label = "Transfer",
                            LabelVi = "Chuyen khoan",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "investment",
                            Color = "#10b981",
                            GradientEnd = "#059669",
                            GradientStart = "#34d399",
                            Icon = "trending-up",
                            Label = "Investment",
                            LabelVi = "Dau tu",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "gift",
                            Color = "#f43f5e",
                            GradientEnd = "#e11d48",
                            GradientStart = "#fb7185",
                            Icon = "card-giftcard",
                            Label = "Gift",
                            LabelVi = "Qua tang",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = "other",
                            Color = "#64748b",
                            GradientEnd = "#475569",
                            GradientStart = "#94a3b8",
                            Icon = "more-horiz",
                            Label = "Other",
                            LabelVi = "Khac",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("BcryptRounds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKeySalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedDataKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyDerivation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyDerivationIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSelectedBankApp", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "PackageName");

                    b.HasIndex("PackageName");

                    b.ToTable("UserSelectedBankApps", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuthenticatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedSessionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstablishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecureChannelAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionKeyAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevokedAtUtc")
                        .HasDatabaseName("IX_UserSessions_RevokedAtUtc");

                    b.HasIndex("UserId", "EstablishedAtUtc")
                        .HasDatabaseName("IX_UserSessions_UserId_EstablishedAtUtc");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetAlertThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompactNumbers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFilterPeriod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilterEndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FilterStartDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeminiApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustomBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long>("MonthlyBudgetMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationPermission")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAICategorization")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAIReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WebhooksEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("NotificationEnabled")
                        .HasDatabaseName("IX_UserSettings_NotificationEnabled");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookDeliveryLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookEndpointId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_WebhookDeliveryLogs_TransactionId");

                    b.HasIndex("Success", "TimestampUtc")
                        .HasDatabaseName("IX_WebhookDeliveryLogs_Success_TimestampUtc");

                    b.HasIndex("WebhookEndpointId", "TimestampUtc")
                        .HasDatabaseName("IX_WebhookDeliveryLogs_WebhookEndpointId_TimestampUtc");

                    b.ToTable("WebhookDeliveryLogs", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Enabled")
                        .HasDatabaseName("IX_WebhookEndpoints_UserId_Enabled");

                    b.HasIndex("UserId", "FailCount")
                        .HasDatabaseName("IX_WebhookEndpoints_UserId_FailCount");

                    b.ToTable("WebhookEndpoints", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookEventSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookEndpointId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEndpointId", "Event")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookEventSubscriptions_WebhookEndpointId_Event");

                    b.ToTable("WebhookEventSubscriptions", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookHeader", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookEndpointId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEndpointId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookHeaders_WebhookEndpointId_Name");

                    b.ToTable("WebhookHeaders", (string)null);
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.BankNotification", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.BankApp", "BankApp")
                        .WithMany("Notifications")
                        .HasForeignKey("BankCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CashTrack.Api.Domain.Entities.Transaction", "ParsedTransaction")
                        .WithOne("SourceNotification")
                        .HasForeignKey("CashTrack.Api.Domain.Entities.BankNotification", "ParsedTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("BankNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankApp");

                    b.Navigation("ParsedTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.CategoryBudget", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.TransactionCategory", "Category")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ClientStorageEnvelope", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("ClientStorageEnvelopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("ImportBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ImportRow", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashTrack.Api.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportBatch");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.BankApp", "BankApp")
                        .WithMany("Transactions")
                        .HasForeignKey("BankCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CashTrack.Api.Domain.Entities.TransactionCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CashTrack.Api.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankApp");

                    b.Navigation("Category");

                    b.Navigation("ImportBatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSelectedBankApp", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.BankApp", "BankApp")
                        .WithMany("SelectedByUsers")
                        .HasForeignKey("PackageName")
                        .HasPrincipalKey("PackageName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("SelectedBankApps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankApp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithOne("Settings")
                        .HasForeignKey("CashTrack.Api.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookDeliveryLog", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.Transaction", "Transaction")
                        .WithMany("WebhookDeliveryLogs")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CashTrack.Api.Domain.Entities.WebhookEndpoint", "WebhookEndpoint")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("WebhookEndpoint");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.UserAccount", "User")
                        .WithMany("WebhookEndpoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookEventSubscription", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.WebhookEndpoint", "WebhookEndpoint")
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEndpoint");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookHeader", b =>
                {
                    b.HasOne("CashTrack.Api.Domain.Entities.WebhookEndpoint", "WebhookEndpoint")
                        .WithMany("Headers")
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEndpoint");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.BankApp", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SelectedByUsers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("Rows");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("SourceNotification");

                    b.Navigation("WebhookDeliveryLogs");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.TransactionCategory", b =>
                {
                    b.Navigation("CategoryBudgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("BankNotifications");

                    b.Navigation("CategoryBudgets");

                    b.Navigation("ClientStorageEnvelopes");

                    b.Navigation("ImportBatches");

                    b.Navigation("SelectedBankApps");

                    b.Navigation("Sessions");

                    b.Navigation("Settings");

                    b.Navigation("Transactions");

                    b.Navigation("WebhookEndpoints");
                });

            modelBuilder.Entity("CashTrack.Api.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Navigation("DeliveryLogs");

                    b.Navigation("EventSubscriptions");

                    b.Navigation("Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
